### ISSUE TITLE
Failing test in basic.js

### ISSUE THREAD

**Issue by Jameskmonger** [tapjs/tap-parser#36]
A test in basic.js appears to be failing, [causing the Travis build to fail](https://travis-ci.org/tapjs/tap-parser/jobs/151142456).

```
test/basic.js ......................................... 5/6
  not ok test/basic.js
    arguments:
      - test/basic.js
    timeout: 30000
    results:
      count: 2
      plan:
        start: 1
        end: 3
      pass: 2
      ok: false
    command: 'C:\Program Files\nodejs\node.exe'
    file: test/basic.js
```

The above is from `npm test` (or `tap test/basic.js`), but when I run `node test/basic.js` I get the following output:

```
λ node test\basic.js
TAP version 13
ok 1 - calling as function returns instance
    # Subtest: passing no options and cb works fine
    1..0
ok 2 - passing no options and cb works fine # time=6.58ms

    # Subtest: takes a buffer just fine
    ok 1 - called cb from normal write
    ok 2 - called cb from post-bailout write
    ok 3 - should match pattern provided
    1..3
ok 3 - takes a buffer just fine # time=15.09ms

1..3
# time=48.484ms
```
